# Generated by Django 3.2.4 on 2021-07-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('purchase_date', models.DateField()),
                ('working', models.BooleanField()),
            ],
        ),
    ]
