# Generated by Django 3.2.4 on 2021-07-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tech',
            name='release_year',
            field=models.IntegerField(default=2000, verbose_name='release year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tech',
            name='purchase_date',
            field=models.DateField(verbose_name='purchase date'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
