# Generated by Django 3.2.4 on 2021-07-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210707_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='brand',
            field=models.CharField(default='Apple', max_length=50),
            preserve_default=False,
        ),
    ]
